export const symbols = [
  { label: "American Airlines Group Inc", value: "AAL" },
  { label: "Apple Inc", value: "AAPL" },
  { label: "Akebia Therapeutics Inc", value: "AKBA" },
  { label: "AMC Entertainment Holdings Inc", value: "AMC" },
  { label: "Advanced Micro Devices Inc", value: "AMD" },
  { label: "Ampio Pharmaceuticals Inc", value: "AMPE" },
  { label: "Activision Blizzard Inc", value: "ATVI" },
  { label: "Boeing Co", value: "BA" },
  { label: "Bank of America Corporation", value: "BAC" },
  { label: "Biolase Inc", value: "BIOL" },
  { label: "Bristol Myers Squibb Co", value: "BMY" },
  { label: "BP Plc", value: "BP" },
  { label: "Boston Scientific Corporation", value: "BSX" },
  { label: "Citigroup Inc", value: "C" },
  { label: "Cboe Global Markets Inc", value: "CBOE" },
  { label: "Carnival Corp", value: "CCL" },
  { label: "Cinedigm Corporation", value: "CIDM" },
  { label: "Cleveland Cliffs Inc", value: "CLF" },
  { label: "Clovis Oncology Inc", value: "CLVS" },
  { label: "Comcast Corporation", value: "CMCSA" },
  { label: "Cabot Oil and Gas Corp", value: "COG" },
  { label: "ConocoPhillips", value: "COP" },
  { label: "Coty Inc", value: "COTY" },
  { label: "Cisco Systems Inc", value: "CSCO" },
  { label: "Chevron Corporation", value: "CVX" },
  { label: "Delta Air Lines Inc", value: "DAL" },
  { label: "DuPont de Nemours Inc", value: "DD" },
  { label: "Devon Energy Corp", value: "DVN" },
  { label: "eBay Inc", value: "EBAY" },
  { label: "Express Inc", value: "EXPR" },
  { label: "Ford Motor Company", value: "F" },
  { label: "Facebook Inc", value: "FB" },
  { label: "FuelCell Energy Inc", value: "FCEL" },
  { label: "Freeport McMoRan Inc", value: "FCX" },
  { label: "TechnipFMC Limited", value: "FTI" },
  { label: "General Electric Company", value: "GE" },
  { label: "Gilead Sciences Inc", value: "GILD" },
  { label: "General Motors Company", value: "GM" },
  { label: "GameStop Corp Holding Company", value: "GME" },
  { label: "Genworth Financial Inc", value: "GNW" },
  { label: "Barrick Gold Corporation", value: "GOLD" },
  { label: "Gold Resource Corporation", value: "GORO" },
  { label: "Globalstar Inc", value: "GSAT" },
  { label: "Halliburton Co", value: "HAL" },
  { label: "Hecla Mining Company", value: "HL" },
  { label: "International Flavors and Fragrances Inc", value: "IFF" },
  { label: "Inovio Pharmaceuticals Inc New", value: "INO" },
  { label: "Intel Corporation", value: "INTC" },
  { label: "Johnson and Johnson", value: "JNJ" },
  { label: "JP Morgan Chase and Co", value: "JPM" },
  { label: "Kinder Morgan Inc", value: "KMI" },
  { label: "Coca Cola Company", value: "KO" },
  { label: "Kroger Co", value: "KR" },
  { label: "Cheniere Energy Inc", value: "LNG" },
  { label: "Southwest Airlines Co", value: "LUV" },
  { label: "Las Vegas Sands Corp", value: "LVS" },
  { label: "Macys Inc", value: "M" },
  { label: "Contango Oil and Gas Co", value: "MCF" },
  { label: "MGM Resorts International", value: "MGM" },
  { label: "Merck and Co Inc", value: "MRK" },
  { label: "Marathon Oil Corp", value: "MRO" },
  { label: "Morgan Stanley", value: "MS" },
  { label: "Microsoft Corporation", value: "MSFT" },
  { label: "Micron Technology Inc", value: "MU" },
  { label: "Norwegian Cruise Line Holdings Ltd", value: "NCLH" },
  { label: "Annaly Capital Management Inc", value: "NLY" },
  { label: "Northern Oil and Gas Inc", value: "NOG" },
  { label: "Opendoor Technologies Inc", value: "OPEN" },
  { label: "Oracle Corp", value: "ORCL" },
  { label: "Occidental Petroleum Corporation", value: "OXY" },
  { label: "Pfizer Inc", value: "PFE" },
  { label: "Plug Power Inc", value: "PLUG" },
  { label: "QUALCOMM Inc", value: "QCOM" },
  { label: "Ring Energy Inc", value: "REI" },
  { label: "Transocean Ltd", value: "RIG" },
  { label: "Sirius XM Holdings Inc", value: "SIRI" },
  { label: "Schlumberger Ltd", value: "SLB" },
  { label: "SunPower Corporation", value: "SPWR" },
  { label: "Southwestern Energy", value: "SWN" },
  { label: "AT&T Inc", value: "T" },
  { label: "Teradata Corporation", value: "TDC" },
  { label: "TransEnterix Inc New", value: "TRXC" },
  { label: "Tesla Inc", value: "TSLA" },
  { label: "Twitter Inc", value: "TWTR" },
  { label: "TherapeuticsMD Inc", value: "TXMD" },
  { label: "United Airlines Holdings Inc", value: "UAL" },
  { label: "Uranium Energy Corp", value: "UEC" },
  { label: "Ur Energy Inc", value: "URG" },
  { label: "Visa Inc", value: "V" },
  { label: "Verizon Communications Inc", value: "VZ" },
  { label: "Wells Fargo and Company", value: "WFC" },
  { label: "US Steel Corp", value: "X" },
  { label: "Exxon Mobil Corp", value: "XOM" },
  { label: "22nd Century Group Inc", value: "XXII" },
  { label: "Zynga Inc", value: "ZNGA" },
];
